version: "3.8"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - polylot-db:/var/lib/postgresql/data
  server:
    build: .
    ports:
      - 80:8000
    restart: always
    depends_on:
      - db

volumes:
  polylot-db:
    name: polylot-db