version: "3.8"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
    - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
    - PGADMIN_DEFAULT_PASSWORD=admin
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    environment:
      - DATABASE_TYPE=${DATABASE_TYPE}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    restart: always
    depends_on:
      - db
    volumes:
      - .:/polylot